### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DurianCube** [EpicSteve33/BedWars#2]
Genisys Crash Dump Mon May 16 07:07:01 AKDT 2016

Error: syntax error, unexpected end of file
File: /plugins/BedWars-master/src/Epic/BedWars
Line: 343
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[334]         if($color == "0")return "BLACK";
[335]         if($color == "7")return "GRAY";
[336]         if($color == "b")return "AQUA";
[337] 
[338]         return "WHITE";
[339]     }
[340]     public function convertTeamToColor($team){
[341] 
[342]   
[343] 
[344] 
[345] 
[346] 
[347] 
[348] 
[349] 
[350] 
[351] 
[352] 
[353] 

Backtrace:
#0 (): spl_autoload_call(string Epic\Bedwars)
#1 /src/pocketmine/plugin/FolderPluginLoader(48): class_exists(string Epic\Bedwars, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\FolderPluginLoader->loadPlugin(string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\plugins\BedWars-master)
#3 /src/pocketmine/plugin/PluginManager(333): pocketmine\plugin\PluginManager->loadPlugin(string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\plugins\BedWars-master, array Array())
#4 /src/pocketmine/Server(1984): pocketmine\plugin\PluginManager->loadPlugins(string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\plugins\)
#5 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\, string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\, string C:\Users\Administrator\Desktop\1)MiniGames- Genisys\plugins\, string unknown)

Genisys version: 1.1dev #0 [Protocol 60; API 2.0.0]
uname -a: Windows NT WIN-LUM3LB2RHLO 6.2 build 9200 (Windows Server 2012 Datacenter Edition) AMD64
PHP version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

**Comment by EpicSteve33** [comment]
@DurianCube are you using the phar or the latest commit?

**Comment by EpicSteve33** [comment]
@DurianCube This was possibly fixed but I am working on translations before reRelease

**Comment by EpicSteve33** [comment]
Try to See if the release below will work for you now, I have Tested this on ImagicalMine Only and it works, I will close this if you don't respond  

https://github.com/EpicSteve33/BedWars/releases/tag/v0.1

**Comment by DurianCube** [comment]
Im using the latest commit

**Comment by EpicSteve33** [comment]
Try using the phar file I sent a link for

**Comment by EpicSteve33** [comment]
@DurianCube if the issue continues with the phar, then its a genisys issue and I'll have someone help me fix it

**Comment by DurianCube** [comment]
Ok thx 😗
