### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pilock** [EpicSteve33/BedWars#3]
After setting the game, the game can not be join
You can not enter this match
I think the problem is here.
if($text[2] == TextFormat::GREEN."ingresso"){
                    $arena = substr($text[1], 0, -4);
                    $config = new Config($this->getDataFolder()."Arenas/".$arena.".yml", Config::YAML);
                    $status = $config->get("Status");
                    $maxplayers = $config->get("PlayersPerTeam") * $config->get("Teams");
                    $players = count($config->get("Players"));
                    if($status == "Lobby"){
                        if($players < $maxplayers) {
                            $this->TeleportToWaitingLobby($arena, $player);
                            $this->setTeamSelectionItems($player, $arena);
                            $this->addPlayerToArena($arena, $name);
                        } else {
                            $player->sendMessage($this->prefix . TextFormat::RED . "You can not enter this match!");
                        }
                    } else {
                        $player->sendMessage($this->prefix.TextFormat::RED."You can not enter this match!");
                    }
                } else {
                    $player->sendMessage($this->prefix.TextFormat::RED."You can not enter this match!");
                }

**Comment by EpicSteve33** [comment]
This issue is duplicate please comment on the current issue, this will be fix soon
